### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by Furnitureassemblyandfitting** [NIWebDesigns/DanielandSon#1]
![Web site sample](https://user-images.githubusercontent.com/111060125/184129612-734befca-43b3-493b-9572-964d887ee03f.jpg)
![DS2](https://user-images.githubusercontent.com/111060125/184129634-2abfbe15-7d8f-481c-8750-e1ebe6b8aa10.jpg)
![296345279_114557361342538_3169473271118521026_n](https://user-images.githubusercontent.com/111060125/184129667-3a13899a-bcb0-45ad-9b1e-778d590edcba.jpg)

**Comment by itsmat32143** [comment]
Ticket Closed
14/08/2022
02:09
